//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultatie
    {
        public int ID { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<int> MediCId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public Nullable<double> Greutate { get; set; }
        public Nullable<double> Talie { get; set; }
        public Nullable<double> Inaltime { get; set; }
        public Nullable<double> IMC { get; set; }
        public string RezultateAnalize { get; set; }
        public string Diagnostic { get; set; }
        public string Tratament { get; set; }
        public string Observatii { get; set; }
    
        public virtual Medic Medic { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
