//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.Consultaties = new HashSet<Consultatie>();
        }
    
        public int ID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string CNP { get; set; }
        public string Email { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string NrCard { get; set; }
        public string Asigurarea { get; set; }
        public string Alergii { get; set; }
        public string Antecedente_heredocolaterale { get; set; }
        public string Antecedente_personale_patologice { get; set; }
        public string Antecedente_personale_fiziologice { get; set; }
        public string Meseria { get; set; }
        public string LocMunca { get; set; }
        public Nullable<bool> Fumator { get; set; }
        public Nullable<bool> Elev { get; set; }
        public Nullable<bool> Student { get; set; }
        public Nullable<double> Greutate { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Varsta { get; set; }
        public Nullable<System.DateTime> DataNastere { get; set; }
        public Nullable<int> MedicPId { get; set; }
        public string Vaccinuri { get; set; }
        public Nullable<int> Nr_sarcini { get; set; }
        public Nullable<int> Nr_avorturi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultatie> Consultaties { get; set; }
        public virtual Medic Medic { get; set; }
    }
}
